#!/usr/bin/env bash
# Bootstrap dotfiles with dotbot.
#   ./install               link dotfiles + run core setup
#   ./install --packages    also install packages (setup/packages/*)
# Any extra args are forwarded to dotbot.
set -e

CONFIG="install.conf.yaml"
PACKAGES_CONFIG="install.packages.yaml"
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${BASEDIR}" submodule update --init --recursive

run_packages=0
args=()
for a in "$@"; do
    case "$a" in
        --packages) run_packages=1 ;;
        *) args+=("$a") ;;
    esac
done

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${args[@]}"

if [ "${run_packages}" -eq 1 ]; then
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${PACKAGES_CONFIG}" "${args[@]}"
fi
