#!/usr/bin/env bash
# chezmoi: run_once_install-browser-use.sh
# Install browser-use (CDP browser control for agents) for Claude Code and
# opencode.
#
# The skill text is generated by the CLI (`browser-use skill`) rather than
# vendored, so it tracks the installed version instead of drifting from it.
# ~/.claude/skills is a symlink to ~/.config/opencode/skills, so one file
# serves both agents.
#
# Requires a Chrome/Chromium the CLI can reach over CDP; `browser-use doctor`
# reports what is missing. Installing a browser is left to the host — on a
# headless box there may deliberately not be one.
set -euo pipefail

SKILL_DIR="${HOME}/.config/opencode/skills/browser-use"

if ! command -v uv >/dev/null 2>&1; then
    echo "⚠ Skipping browser-use (uv not found)"
    exit 0
fi

if command -v browser-use >/dev/null 2>&1; then
    echo "✓ browser-use already installed"
else
    echo "Installing browser-use..."
    uv tool install browser-use
fi

# Telemetry is on by default and phones home with an install id.
browser-use telemetry disable >/dev/null 2>&1 || true

mkdir -p "$SKILL_DIR"
if browser-use skill > "${SKILL_DIR}/SKILL.md" 2>/dev/null && [ -s "${SKILL_DIR}/SKILL.md" ]; then
    echo "✓ browser-use skill written for Claude Code + opencode"
else
    rm -f "${SKILL_DIR}/SKILL.md"
    echo "⚠ browser-use skill generation failed" >&2
fi

echo "✓ browser-use setup done"
